micronaut:
    application:
        name: beersocket
                
#Uncomment to set server port
#    server:
#        port: 8085
---
consul:
    client:
        registration:
            enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"