micronaut:
    application:
        name: beersocket
                
#Uncomment to set server port
    server:
        port: ${random.port}
---
consul:
    client:
        registration:
            enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"