micronaut:
    application:
        name: beer-waiter
                
#Uncomment to set server port
#    server:
#        port: 8080
---
kafka:
    #  embedded:
    #    enabled: true
    bootstrap:
        servers: "${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}"